### ISSUE TITLE
Error while checking yandex: Timed out connecting to mx.yandex.ru. on port 25

### ISSUE THREAD

**Issue by GreenAA** [sharsil/mailcat#43]
Using proxy http://1.2.3.4:8080 to make requests...
Error while checking gmail: Timed out connecting to alt1.gmail-smtp-in.l.google.com. on port 25
Error while checking yandex: Timed out connecting to mx.yandex.ru. on port 25
Error while checking mailDe: Timed out connecting to mx01.mail.de. on port 25

if i using --tor / proxy / only use i get error , why ?

**Comment by GreenAA** [comment]
Support?

**Comment by soxoj** [comment]
Hi, thanks for the report, I'll check it

**Comment by soxoj** [comment]
The problem is not in proxy, cause Mailcat use SMTP requests to check yandex/gmail/mailDe.
I believe that the root cause is in many parallel proxied requests, influencing the work with sockets for SMTP checks. It could happen because of the non-optimal launching of all checks, and it could be fixed.

Please, try the following new version: https://github.com/sharsil/mailcat/tree/outlook-executor-fixes 
1. Run it with proxy only
2. Run it with an increased timeout (e.g. -t 20) and less parallel connections (-m 5) if the problem persists

**Comment by GreenAA** [comment]
thanks bro you the best
